export const GET_USER = "GET_USER";
export const USER_ERROR = "USER_ERROR";
export const GET_PRODUCT_DETAILS="GET_PRODUCT_DETAILS";
export const Get_CATEGORIES_DETAILS="Get_CATEGORIES_DETAILS";
export const GET_COUPONS_DETAILS="GET_COUPONS_DETAILS"
export const APPLY_COUPON ="APPLY_COUPON"
export const CHECKOUT_DATA="CHECKOUT_DATA"
export const CHECKOUT_GET_DATA="CHECKOUT_GET_DATA"
export const POST_API_DATA="POST_API_DATA"
export const PAYMENT_GATEWAYS="PAYMENT_GATEWAYS"
export const GET_SHIPPING_METHODS="GET_SHIPPING_METHODS"
export const GET_SHIPPING_METHODS_DATA="GET_SHIPPING_METHODS_DATA"
export const CART_DATA = "CART_DATA";
export const DELETE_ITEM= "DELETE_ITEM";
export const UPDATE_CART_QTY="UPDATE_CART_QTY";



